aggregator_logs/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('log_access_apache.urls')),
    path('', include('main.urls')),
]

api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from .views import LogAccessApacheList, LogAccessApacheDetail


urlpatterns = [
    path('logs-list/', LogAccessApacheList.as_view(), name='api-logs-list'),
    path('log/<int:pk>/', LogAccessApacheDetail.as_view(), name="api-log-detail"),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]

log_access_apache/urls.py
from django.urls import path

from .views import LogDetailView, LogAccessApacheFilterView

urlpatterns = [

    path('', LogAccessApacheFilterView.as_view(), name='logs_list'),
    path('<int:pk>/', LogDetailView.as_view(), name='log_detail'),

]

main/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from .views import SignUpView, MainLoginView

app_name = "main"

urlpatterns = [

    path("register/", SignUpView.as_view(), name="register"),
    path("login/", MainLoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name= "logout"),
]

api/models.py
from django.db import models

# Create your models here.

log_access_apache/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class LogAccessApacheModel(models.Model):
    host = models.GenericIPAddressField(
        _('Remote hostname'),
        null=False,
        blank=False,
        db_index=True,
    )
    logname = models.CharField(
        _('Remote logname'),
        max_length= 100,
        null=True,
        blank=True,
    )
    user = models.CharField(
        _('Remote user'),
        max_length= 100,
        null=True,
        blank=True,
    )
    date = models.DateTimeField(
        _('Request time'),
        null=False,
        blank=False,
        db_index=True,
    )
    request_line = models.TextField(
        _('First request line'),
        null=True,
        blank=True,
    )
    status = models.PositiveSmallIntegerField(
        _('Status'),
        null=True,
        blank=True,
    )
    bytes = models.PositiveIntegerField(
        _('Size response in bytes'),
        null=True,
        blank=True,
    )
    referer = models.TextField(
        _('Referer'),
        null=True,
        blank=True,
    )
    user_agent = models.TextField(
        _('User-Agent'),
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.host

    class Meta:
        ordering = ['date', 'host']
        verbose_name = "Log Access Apache"
        verbose_name_plural = "Logs Access Apache"


class FileLogModel(models.Model):
    date = models.DateTimeField(
        _('Data logging'),
        auto_now=True,
    )
    path_file = models.TextField(
        _('Path file'),
        null=False,
        blank=False,
        unique=True,
        db_index=True,
    )
    last_line = models.TextField(
        _('Last line'),
        null=False,
        blank=True,
        default='',
    )
    last_position = models.PositiveBigIntegerField(
        _('Last position'),
        null=False,
        blank=False,
        default=0,
    )

    def __str__(self):
        return self.path_file

    @classmethod
    def get_filelog_and_check_last_position(cls, file):
        """
        check a read new file or no
        if new: read from the start,
        else: compare last_line in db and last line file in last position
            if last_line matched: read next lines
            else: we consider that the file was cleared and read from the beginning
        """
        file_log, create = FileLogModel.objects.get_or_create(path_file=file.name)

        if not create and (file_log.last_line or file_log.last_position):
            # calculate start last line
            start_last_line = file_log.last_position - len(file_log.last_line)
            file.seek(start_last_line)
            last_line_in_file = file.readline()
            if not last_line_in_file or last_line_in_file != file_log.last_line:
                file_log.last_line=''
                file_log.last_position=0
                file_log.save()
        return file_log


    class Meta:
        ordering = ['date']
        verbose_name = "File Log"
        verbose_name_plural = "File Logs"

log_access_apache/forms.py
from django import forms

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name']

api/views.py
from django_filters import rest_framework as filters
from rest_framework import generics

from log_access_apache.models import LogAccessApacheModel
from .serializers import LogAccessApacheSerializer
from .filters import LogAccessApacheFilter


class LogAccessApacheList(generics.ListAPIView):
    queryset = LogAccessApacheModel.objects.all()
    serializer_class = LogAccessApacheSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class=LogAccessApacheFilter


class LogAccessApacheDetail(generics.RetrieveAPIView):
    queryset = LogAccessApacheModel.objects.all()
    serializer_class = LogAccessApacheSerializer

log_access_apache/views.py
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django_filters.views import FilterView

from .models import LogAccessApacheModel
from .filters import LogAccessApacheFilter


class LogAccessApacheFilterView(LoginRequiredMixin, FilterView):
    template_name = "logs/logs_list.html"
    model = LogAccessApacheModel
    paginate_by = 100
    filterset_class = LogAccessApacheFilter


class LogDetailView(LoginRequiredMixin, DetailView):
    model = LogAccessApacheModel
    template_name = "logs/log_detail.html"

main/views.py
from django.shortcuts import  redirect
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import UserRegisterForm


class MainLoginView(SuccessMessageMixin, LoginView):
    template_name="main/login.html"
    success_message = "You are logged in!!!"
    redirect_authenticated_user=True

class SignUpView(SuccessMessageMixin, CreateView):
    template_name = 'main/register.html'
    success_url = reverse_lazy('main:login')
    form_class = UserRegisterForm
    success_message = "You are registered, now login."
    redirect_authenticated_user=True

    def get(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            return redirect('logs_list')
        return super().get(request, *args, **kwargs)

templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Aggregator Log|{% block title %}Main{% endblock %}</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand h1 my-0" href="/">Aggregator Log{% if user.get_username %} (Welcome, {{user.get_username}}){% endif %}</a>
      <a class="nav-link active me-auto" aria-current="page" href={% url 'logs_list' %}>{% if user.is_authenticated %}All Logs{% endif %}</a>

      {% if user.is_authenticated %}
        <a type="button" class="btn btn-lg text-nowrap btn-danger" href={% url 'main:logout' %}>Exit</a>
      {% else %}
        <a type="button" class="btn btn-lg text-nowrap btn-primary" href={% url 'main:login' %}>Login</a>
      {% endif %}

    </div>
  </nav>
  <!-- Messages -->
  <div class="toast-container position-absolute top-0 end-0 p-3">
    {% if messages %}
      <div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
      {% for message in messages %}
        <div class="toast-header">
        {% if message.extra_tags %}<strong class="me-auto">{{ message.extra_tags }}</strong>{% endif %}
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Закрыть"></button>
        </div>
      <div class="toast-body">{{ message }}</div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
  {% block content %}
  {% endblock %}
</body>
</html>

templates/logs/log_detail.html
{% extends 'layout/basic.html' %}
{% block title %}Detail Log{% endblock  %}

{% block content %}
<div class="container">
  {% if object %}
  <table class="table table-sm my-3">
    <thead>
      <tr>
        <th scope="col">&nbsp;</th>
        <th scope="col">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row" class="text-nowrap">Remote host (IP)</th>
        <td class="text-nowrap">{{ object.host }}</td>
      </tr>
      <tr>
        <th scope="row" class="text-nowrap">Remote logname</th>
        <td class="text-nowrap">{% if object.logname %}{{ object.logname }}{% else %}-{% endif %}</td>
      </tr>
      <tr>
        <th scope="row" class="text-nowrap">Remote user</th>
        <td class="text-nowrap">{% if object.user %}{{ object.user }}{% else %}-{% endif %}</td>
      </tr>
      <tr>
        <th scope="row" class="text-nowrap">Date</th>
        <td class="text-nowrap">{{ object.date|date:"d.m.Y G:i:s" }}</td>
      </tr>
      <tr>
        <th scope="row" class="text-nowrap">First request line</th>
        <td>{% if object.request_line %}{{ object.request_line }}{% else %}-{% endif %}</td>
      </tr>
      <tr>
        <th scope="row" class="text-nowrap">Status</th>
        <td class="text-nowrap">{{ object.status }}</td>
      </tr>
      <tr>
        <th scope="row" class="text-nowrap">Size response (bytes)</th>
        <td class="text-nowrap">{% if object.bytes %}{{ object.bytes|filesizeformat }}{% else %}-{% endif %}</td>
      </tr>
      <tr>
        <th scope="row" class="text-nowrap">Referer</th>
        <td>{% if object.referer %}{{ object.referer }}{% else %}-{% endif %}</td>
      </tr>
      <tr>
        <th scope="row" class="text-nowrap">User-agent</th>
        <td>{% if object.user_agent %}{{ object.user_agent }}{% else %}-{% endif %}</td>
      </tr>
    </tbody>
  </table>
  {% endif %}
  <a href={% if request.META.HTTP_REFERER %}{{ request.META.HTTP_REFERER }}{% else %}{% url 'logs_list' %}{% endif %} class="btn btn btn-outline-primary">&laquo; Back</a>
</div class="container">
{% endblock content %}

templates/logs/logs_list.html
{% extends 'layout/basic.html' %}
{% block title %}All Logs{% endblock  %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <!--Filter-->
  <form class="row gx-3 gy-2 gy-md-0 mx-2 my-3">
    {{ filter.form|crispy }}
    <div class="col-12 my-1">
      <button type="submit" class="btn btn-sm btn-outline-primary">Фильтр</button>
      <a href={% url 'logs_list' %} class="btn btn-sm btn btn-outline-danger">Сброс</a>
    </div>
  </form>
  {% if object_list %}
  <!--Pagination-->
  {% include 'partials/_pagination.html' %}
  <!--Teble Items-->
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">IP</th>
        <th scope="col">Date</th>
        <th scope="col" class="text-nowrap">First request line</th>
        <th scope="col">Status</th>
        <th scope="col" class="text-nowrap">Size (bytes)</th>
        <th scope="col">Show</th>
      </tr>
    </thead>
    <tbody>
      {% for log in object_list %}
        <tr>
          <th scope="row" class="text-nowrap">{{ log.host }}</th>
          <td class="text-nowrap">{{ log.date|date:"d.m.Y G:i:s" }}</td>
          <td>{{ log.request_line }}</td>
          <td class="text-nowrap">{{ log.status }}</td>
          <td class="text-nowrap">{% if log.bytes %} {{ log.bytes|filesizeformat  }} {% else %} - {% endif %}</td>
          <td><a href={% url 'log_detail' log.pk %} class="btn btn-sm btn btn-outline-success">View</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <!--Pagination-->
  {% include 'partials/_pagination.html' %}
  {% else %}
    <h2>Nothing found</h2>
  {% endif %}
</div class="container">
{% endblock content %}

templates/main/login.html
{% extends "layout/basic.html" %}
{% block title %}Login{% endblock  %}

{% block content %}
{% load crispy_forms_tags %}
<!--Login-->
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>
{% endblock %}

templates/main/register.html
{% extends "layout/basic.html" %}
{% block title %}Register{% endblock  %}

{% block content %}
{% load crispy_forms_tags %}
<!--Register-->
<div class="container py-5">
  <h1>Register</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" type="submit">Register</button>
  </form>
  <p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>
{% endblock %}

templates/partials/_pagination.html
{% load tag_paginator %}

{% if is_paginated %}
<nav>
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">&laquo; First</a></li>
      <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a></li>
    {% endif %}
    <li class="page-item disabled"><a class="page-link" href="#">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">Next</a></li>
      <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.paginator.num_pages %}">Last &raquo;</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}